[project]
name = "simple-process-bigraph-runtime"
version = "0.1.0"
description = ""
authors = [
    {name = "Logan Drescher",email = "drescher@uchc.edu"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.10, <4.0"
packages = [
    {include = "simple_process_bigraph_runtime"},
    {include = "tests"}
]
dependencies = [
    "process-bigraph (>=0.0.35, <1.0)",
    "typer (>=0.15.3, <1.0)",
#    "process-bigraph-lang @ git+https://github.com/biosimulations/process-bigraph-lang.git#bind-to-object",
    "process-bigraph-lang @ ../process-bigraph-lang",
    "spatio-flux @ git+https://github.com/vivarium-collective/spatio-flux.git",
    "vivarium-interface (>=0.0.5,<0.0.6)"
]

[tool.poetry]

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
pytest-cov = "^6.1.1"
deptry = "^0.23.0"
mypy = "^1.15.0"
pre-commit = "^4.2.0"
tox = "^4.25.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
