[project]
name = "simple-process-bipgraph-runtime"
version = "0.1.0"
description = ""
authors = [
    {name = "Logan Drescher",email = "drescher@uchc.edu"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "process-bigraph"
]

[tool.poetry]
packages = [{include = "simple_process_bipgraph_runtime", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
